WithSecure/ShipmentDispatchApp/force-app/main/default/objects/DispatchCarrier__c/DispatchCarrier__c.object-meta.xml
<CustomObject>
    <label>Dispatch Carrier</label>
    <nameField>
        <label>Shipment Request Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DispatchCarriers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WithSecure/ShipmentDispatchApp/force-app/main/default/objects/DispatchCarrier__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Shipment status updated to Dispatched and Dispatch Failed.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dispatching</fullName>
            </value>
            <value>
                <fullName>Dispatched</fullName>
            </value>
            <value>
                <fullName>Dispatch Failed</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

WithSecure/ShipmentDispatchApp/force-app/main/default/classes/DispatchStatusUpdaterBatch.cls
/**
 * @description       : 
 * @author            : Manigandan Dhamodaran
 * @group             : 
 * @last modified on  : 07-01-2025
 * @last modified by  : Manigandan Dhamodaran
 *  * @group ShipmentDispatchApp
**/
global class DispatchStatusUpdaterBatch implements Database.Batchable<SObject> {

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator([
            SELECT Id, Status__c 
            FROM DispatchCarrier__c 
            WHERE Status__c = 'Dispatching'
        ]);
    }

    global void execute(Database.BatchableContext bc, List<DispatchCarrier__c> scope) {
        List<DispatchCarrier__c> toUpdate = new List<DispatchCarrier__c>();
        Boolean assignDispatched = true; // Start with 'Dispatched'

        for (DispatchCarrier__c record : scope) {
            record.Status__c = assignDispatched ? 'Dispatched' : 'Dispatch Failed';
            assignDispatched = !assignDispatched; // Toggle for next record
            toUpdate.add(record);
        }

        if (!toUpdate.isEmpty()) {
            update toUpdate;
        }
    }

    global void finish(Database.BatchableContext bc) {
        System.debug('DispatchStatusUpdaterBatch completed.');
        scheduleNextBatch();
    }

    global void scheduleNextBatch() {
        String datetimeVal = DateTime.now().format('yyyyMMdd_HHmmss');
        Integer intervalVal = 10;
        if (!Test.isRunningTest()) {
            System.scheduleBatch(
                new DispatchStatusUpdaterBatch(),
                'DispatchStatusUpdaterBatch_' + DatetimeVal,
                intervalVal
            );
        } 
    }
}