WithSecure/ShipmentDispatchApp/force-app/main/default/objects/DispatchCarrier__c/DispatchCarrier__c.object-meta.xml
<CustomObject>
    <label>Dispatch Carrier</label>
    <nameField>
        <label>Shipment Request Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DispatchCarriers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

WithSecure/ShipmentDispatchApp/force-app/main/default/objects/DispatchCarrier__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <description>Org A Shipment record Id</description>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

WithSecure/ShipmentDispatchApp/force-app/main/default/objects/DispatchCarrier__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Shipment status updated to Dispatched and Dispatch Failed.</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dispatching</fullName>
            </value>
            <value>
                <fullName>Dispatched</fullName>
            </value>
            <value>
                <fullName>Dispatch Failed</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

WithSecure/ShipmentDispatchApp/force-app/main/default/objects/DispatchCarrier__c/fields/Tracking_ID__c.field-meta.xml
<CustomField>
    <fullName>Tracking_ID__c</fullName>
    <description>Tracking Id of Shipment</description>
    <label>Tracking ID</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

WithSecure/ShipmentDispatchApp/force-app/main/default/classes/DispatchStatusUpdaterSchedulerTest.cls
/**
 * @description       : 
 * @author            : Manigandan Dhamodaran
 * @group ShipmentDispatchApp
 * @last modified on  : 06-26-2025
 * @last modified by  : Manigandan Dhamodaran
**/
@isTest
private class DispatchStatusUpdaterSchedulerTest {

    @isTest static void testSchedulerFiresBatch() {
        // Create some dispatching records
        List<DispatchCarrier__c> testRecords = new List<DispatchCarrier__c>();
        for (Integer i = 0; i < 6; i++) {
            testRecords.add(new DispatchCarrier__c(
                Name = 'Test Shipment ' + i,
                Status__c = 'Dispatching',
                Tracking_Id__c = 'Tracking_' + i,
                External_Id__c = 'SR' + i
            ));
        }
        insert testRecords;

        Test.startTest();
        String jobId = System.schedule(
            'TestScheduler',
            '0 0 0 1 1 ? 2050',  // Dummy cron
            new DispatchStatusUpdaterScheduler());
        Test.stopTest();
        // Verify results
        System.assertNotEquals(null, jobId, 'Job should be scheduled successfully.');
        }
}