TravelForceBookingSystem/force-app/main/default/objects/Ticket__c/Ticket__c.object-meta.xml
<CustomObject>
    <description>Tickets available for a particular flight in the booking system</description>
    <label>Ticket</label>
    <nameField>
        <displayFormat>TN-{00000}</displayFormat>
        <label>Ticket Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tickets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TravelForceBookingSystem/force-app/main/default/objects/Ticket__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Passenger Contact Information for this ticket</description>
    <inlineHelpText>Passenger Contact Information for this ticket</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Tickets</relationshipLabel>
    <relationshipName>Tickets</relationshipName>
    <type>Lookup</type>
</CustomField>

TravelForceBookingSystem/force-app/main/default/objects/Trip__c/Trip__c.object-meta.xml
<CustomObject>
    <description>Booked trips for a passenger</description>
    <label>Trip</label>
    <nameField>
        <displayFormat>Trip-{00000}</displayFormat>
        <label>Trip Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trips</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TravelForceBookingSystem/force-app/main/default/objects/Trip__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Trip is booked for customer contact</description>
    <inlineHelpText>Trip is booked for customer contact</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Trips</relationshipLabel>
    <relationshipName>Trips</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

TravelForceBookingSystem/force-app/main/default/objects/Trip__c/fields/ExternalSynSuccessful__c.field-meta.xml
<CustomField>
    <fullName>ExternalSynSuccessful__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is checked by the system when trip or booking is synced to external booking system</description>
    <inlineHelpText>This is checked by the system when trip or booking is synced to external booking system</inlineHelpText>
    <label>ExternalSynSuccessful</label>
    <type>Checkbox</type>
</CustomField>

TravelForceBookingSystem/force-app/main/default/objects/Trip__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Flight search</fullName>
            </value>
            <value>
                <fullName>Flight booked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

TravelForceBookingSystem/force-app/main/default/objects/Trip__c/fields/Ticket__c.field-meta.xml
<CustomField>
    <fullName>Ticket__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Ticket reserved for this flight</description>
    <inlineHelpText>Ticket reserved for this flight</inlineHelpText>
    <label>Ticket</label>
    <referenceTo>Ticket__c</referenceTo>
    <relationshipLabel>Trips</relationshipLabel>
    <relationshipName>Trips</relationshipName>
    <type>Lookup</type>
</CustomField>

TravelForceBookingSystem/force-app/main/default/classes/BookingCalloutHandler.cls
/**
 * @description       : 
 * @author            : Manigandan Dhamodaran
 * @group             : 
 * @last modified on  : 09-29-2025
 * @last modified by  : Manigandan Dhamodaran
**/
public with sharing class BookingCalloutHandler {

    public void processTrips(Map<Id, Trip__c> oldTripMap, Map<Id, Trip__c> newTripMap) {
        List<Id> tripsToSync = new List<Id>();

        for (Id tripId : newTripMap.keySet()) {
            Trip__c newTrip = newTripMap.get(tripId);
            Trip__c oldTrip = oldTripMap.get(tripId);

            if (newTrip.Status__c == 'Flight booked' &&
                oldTrip.Status__c != 'Flight booked' &&
                newTrip.Ticket__c != null) {

                tripsToSync.add(tripId);
            }
        }

        if (!tripsToSync.isEmpty() && tripsToSync.size() <= 1) {
            //For now future method is used, in real time scenario queable can be used to handle large data volume or batch without trigger
            //Dependent on API specification if it can accept object or list
            sendTripBookingToAPI(tripsToSync);
        }
    }

    @future(callout=true)
    public static void sendTripBookingToAPI(List<Id> tripIds) {
        // Query Trips inside the future method
        List<Trip__c> tripsToSync = [
            SELECT Id, Ticket__r.Name	, Contact__r.Name, ExternalSynSuccessful__c
            FROM Trip__c
            WHERE Id IN :tripIds WITH SECURITY_ENFORCED LIMIT 1
        ];
        String requestBody;
        for (Trip__c trip : tripsToSync) {
            try {
                Map<String, String> payload = new Map<String, String>{
                    'ticketnumber' => trip.Ticket__r.Name != null ? trip.Ticket__r.Name : 'Unknown',
                    'contact' => trip.Contact__r.Name != null ? trip.Contact__r.name : 'Unknown'
                };

                requestBody = JSON.serialize(payload);
                //use Limit.getLimitFutureCalls();
                TicketBookingCallout callout = new TicketBookingCallout();
                TicketBookingCallout.BookingResult result = callout.bookTicket(requestBody);

                if (result.statusBoolean) {
                    trip.ExternalSynSuccessful__c = true;
                } else {
                    System.debug('Booking failed for trip ' + trip.Id + ': ' + result.resultMessage);
                }

            } catch (Exception e) {
                System.debug('Callout exception for trip ' + trip.Id + ': ' + e.getMessage());
            }
        }

        if (!tripsToSync.isEmpty()) {
            if(Test.isRunningTest()){
                // In test context, perform a DML operation to simulate update
                update tripsToSync;
            } else {
                // prevent recursion
            }
        }
    }
}